server:
  port: 8080
spring:
  application:
    name: springbootdemo
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
  ########################################################
  ###DATASOURCE
  ########################################################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      #数据库连接地址
#      url: jdbc:mysql://180.167.245.106:13306/shdq_dev?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      #用户名
#      username: shdq
      #密码
#     password: shdq_dev
      url: jdbc:mysql://103.24.116.110:53306/cpic_test?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      #用户名
      username: tpy_dev
      #密码
      password: tpy#20!8
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  #typeAliasesPackage: com.xuzw.dao.entity
  mapperLocations: classpath:mapper/**/*.xml


